# 设定模型训练参数

# Device to use for training, 'cpu' or 'cuda'
device: cuda

# Number of epochs to train the model
epoch: 40

# path to save the trained model
save: ./saved_models/

# Batch size used during training
batch_size: 32

# Model architecture to use
model: ResNet18

# Optimizer to use for training
optimizer: SGD

# Learning rate used by the optimizer
lr: 0.001

# Momentum used by the optimizer
momentum: 0.9

# Train/Validation split ratio
rate: 0.8

# Directory containing the training data
data_dir: C:\Users\Lai\Documents\GitHub\DLlab\lab3\plant-seedlings-classification

#
model_path: ./bestmodel.pth